"""Change countries schema

Revision ID: 26a9da2b58b6
Revises: 700ebc8931b1
Create Date: 2025-01-03 21:43:08.786184

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26a9da2b58b6"
down_revision: str | None = "700ebc8931b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("countries", "status", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("countries", "status", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
