"""Add status col

Revision ID: 32bd18ce7211
Revises: 049cc87131ac
Create Date: 2025-01-03 23:27:07.199819

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32bd18ce7211"
down_revision: str | None = "049cc87131ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("status", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "status")
    # ### end Alembic commands ###
