"""Change countries schema

Revision ID: 700ebc8931b1
Revises: 1db25dc4afe7
Create Date: 2025-01-03 21:40:24.148835

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "700ebc8931b1"
down_revision: str | None = "1db25dc4afe7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("countries", sa.Column("iso2", sa.String(), nullable=True))
    op.add_column("countries", sa.Column("parent_iso3", sa.String(), nullable=True))
    op.alter_column("countries", "iso3", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("countries", "color_code")
    op.drop_column("countries", "iso_3166_1_alpha_2_codes")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "countries",
        sa.Column(
            "iso_3166_1_alpha_2_codes",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "countries",
        sa.Column("color_code", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.alter_column("countries", "iso3", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("countries", "parent_iso3")
    op.drop_column("countries", "iso2")
    # ### end Alembic commands ###
