"""Add svg bucket col

Revision ID: b32de750880e
Revises: cb702ad590af
Create Date: 2025-01-03 22:47:13.452785

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b32de750880e"
down_revision: str | None = "cb702ad590af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("countries", sa.Column("svg_bucket_path", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("countries", "svg_bucket_path")
    # ### end Alembic commands ###
