"""Change countries schema

Revision ID: cb702ad590af
Revises: 26a9da2b58b6
Create Date: 2025-01-03 21:43:45.743775

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb702ad590af"
down_revision: str | None = "26a9da2b58b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("countries", "continent", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("countries", "region", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("countries", "region", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "countries", "continent", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
