services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN}
    depends_on:
      - nginx
    container_name: worldle-cloudflared

  api:
    container_name: worldle-api
    build:
      context: .
      dockerfile: backend/Dockerfile
    command:
      [
        "gunicorn",
        "worldle.api.main:app",
        "--workers",
        "4",
        "--worker-class",
        "uvicorn.workers.UvicornWorker",
        "--bind",
        "0.0.0.0:80",
      ]
    volumes:
      - worldle_data:/data
    environment:
      - DATA_ROOT=/data
      - RL_DEBUG=0
    env_file:
      - credentials.env
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - WORLDLE_API_URL=/api
    container_name: worldle-frontend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
      - frontend
    restart: unless-stopped

volumes:
  worldle_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/worldle
