// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options,
  createClient,
  createConfig,
} from "@hey-api/client-fetch";
import type {
  ListCountriesError,
  ListCountriesResponse,
  ReadCountryData,
  ReadCountryError,
  ReadCountryResponse,
} from "./types.gen";

export const client = createClient(createConfig());

export class DefaultService {
  /**
   * List Countries
   */
  public static listCountries<ThrowOnError extends boolean = false>(
    options?: Options<unknown, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      ListCountriesResponse,
      ListCountriesError,
      ThrowOnError
    >({
      ...options,
      url: "/countries",
    });
  }

  /**
   * Read Country
   */
  public static readCountry<ThrowOnError extends boolean = false>(
    options: Options<ReadCountryData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      ReadCountryResponse,
      ReadCountryError,
      ThrowOnError
    >({
      ...options,
      url: "/countries/{country_id}",
    });
  }
}
