// This file is auto-generated by @hey-api/openapi-ts

export type CountryItem = {
  id: number;
  name: string;
  iso2: string | null;
  iso3: string | null;
  status: string | null;
  continent: string | null;
  region: string | null;
  parent_id: number | null;
};

export type CountryRead = {
  id: number;
  name: string;
  iso2: string | null;
  iso3: string | null;
  status: string | null;
  continent: string | null;
  region: string | null;
  parent_id: number | null;
  geometry: GeoJson;
  geo_point: GeoJson;
};

export type GeoJson = {
  type: "Feature";
  geometry: GeoJsonGeometry;
  properties: {
    [key: string]: unknown;
  } | null;
};

export type type = "Feature";

export const type = {
  FEATURE: "Feature",
} as const;

export type GeoJsonGeometry = {
  type: GeoJsonGeometryType;
  coordinates: Array<unknown>;
};

export type GeoJsonGeometryType =
  | "Point"
  | "LineString"
  | "Polygon"
  | "MultiPolygon"
  | "MultiLineString";

export const GeoJsonGeometryType = {
  POINT: "Point",
  LINE_STRING: "LineString",
  POLYGON: "Polygon",
  MULTI_POLYGON: "MultiPolygon",
  MULTI_LINE_STRING: "MultiLineString",
} as const;

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type ListCountriesResponse = Array<CountryItem>;

export type ListCountriesError = unknown;

export type ReadCountryData = {
  path: {
    country_id: number;
  };
};

export type ReadCountryResponse = CountryRead;

export type ReadCountryError = HTTPValidationError;
